### ISSUE TITLE
Authentication error running kubectl proxy

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#10115]
I followed the explorer example but when I did:

`
curl localhost:8001/api/v1/proxy/namespaces/default/pods/explorer:8080/vars/
`

It returns <h3>Unauthorized</h3>

Maybe something changed in auth/z that the example stop working?  @lavalamp

**Comment by lavalamp** [comment]
@mikedanese hm--maybe something broke at head recently?

**Comment by mikedanese** [comment]
Tested out #10105 and it seems to fix it. @brendanburns @caesarxuchao

**Comment by mikedanese** [comment]
This is fixed on HEAD

**Comment by lavalamp** [comment]
Is it? I just sync'd to head and I still have this problem?

**Comment by lavalamp** [comment]
OK, I see-- paths that start with /api/ work now, but paths that don't (e.g. /ui/) are still broken. You have to pass --api-prefix=/ to access these paths.

**Comment by lavalamp** [comment]
I see. The issue is that the default accepted/rejected things don't allow anything but /api. @brendandburns did you exclude the UI on purpose?

**Comment by lavalamp** [comment]
I will fix this breakage.

**Comment by lavalamp** [comment]
I'll include my fix in #10070. I'm also adding tests so that I don't have to make this work a third time.

**Comment by ddysher** [comment]
:+1:
