### ISSUE TITLE
kube2sky failing with "Failed to list *api.Service: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by jamiehannaford** [GoogleCloudPlatform/kubernetes#12534]
I'm trying to setup SkyDNS according to [these docs](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/dns), but it's not working when I use these [skydns-rc.yaml](https://gist.github.com/jamiehannaford/268a2f48d3a750fbd2a8) and [skydns-svc.yaml](https://gist.github.com/jamiehannaford/033a93a50e3a4ec68d24) files.

I read in [various](https://github.com/GoogleCloudPlatform/kubernetes/issues/11101) [issues](https://github.com/pires/kubernetes-vagrant-coreos-cluster/issues/96) that there was some kind of auth problem for v0.18, but I'm running a newer version of kubectl so I don't think that's the problem:

```bash
kubernetes-master ~ # kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}
```

I originally used [these docs](), but the pod kept restarting every 30 seconds. Once I switched to the docs I linked to above, it no longer restarted:

```bash
kubernetes-master ~ # kubectl get pods --namespace=kube-system
NAME                READY     STATUS    RESTARTS   AGE
kube-dns-v8-l7qdb   4/4       Running   0          15m
```

But it's not working:

```bash
kubernetes-master ~ # kubectl exec kube-dns-v8-l7qdb --namespace=kube-system -c skydns nslookup kubernetes.default.cluster.local
nslookup: can't resolve 'kubernetes.default.cluster.local'
Server:    69.20.0.164
Address 1: 69.20.0.164 cachens1.iad1.rackspace.com
```

Here are the logs:

```bash
kubernetes-master ~ # kubectl logs kube-dns-v8-l7qdb skydns --namespace=kube-system
2015/08/11 15:19:21 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [1]
2015/08/11 15:19:21 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/08/11 15:19:21 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
```
```bash
kubernetes-master ~ # kubectl logs kube-dns-v8-l7qdb kube2sky --namespace=kube-system
E0811 15:35:36.952358       1 reflector.go:136] Failed to list *api.Endpoints: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
E0811 15:35:36.952516       1 reflector.go:136] Failed to list *api.Service: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
```

What can I do to fix this problem? 

Also, is there any way to discover where the config file for the kubelet agent resides on the minion hosts? The docs say you need to edit the config to add `--cluster-dns`, but I can't find the config file.

**Comment by guybrush** [comment]
maybe this helps: https://gist.github.com/guybrush/47bcd5f4e41a3be102b2#gistcomment-1491790

**Comment by jamiehannaford** [comment]
@guybrush I also read your gist! :smile: But I had trouble extrapolating to my scenario. 

Is it [these lines](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/kubectl-container/pod.json#L37-L44) I need to add (obviously in YAML) to the RC file?

Where do I specify the `--cluster-dns` IP? In a config file? If so, what path? Can it be any arbitrary IP on the subnet?

Why did you change your subnet range? I don't think that's relevant to my problem.

**Comment by guybrush** [comment]
sorry the gist (and comment) are not complete, I pushed my working branch here: https://github.com/guybrush/kubernetes/commit/e6070a7179e7ef69387e4f9851b9648aa23f1518

you can test it with

```
git clone https://github.com/guybrush/kubernetes
cd kubernetes
git checkout local-cluster-up-with-dns
sudo hack/local-up-cluster.sh
# in another terminal:
cd kubernetes
cluster/kubectl.sh create -f dns
cat << EOF | cluster/kubectl.sh create -f -
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
EOF
# wait a second or two
cluster/kubectl.sh exec busybox -ti nslookup kubernetes
```

**Comment by jamiehannaford** [comment]
@guybrush Didn't work. I'm running CoreOS in a multi-node cluster (1 master, 3 minion hosts), so I couldn't compile a custom kubectl binary. Instead I recreated your steps with the `kubectl` already installed (the version info is in original post above).

I copied your [two DNS files](https://github.com/guybrush/kubernetes/tree/e6070a7179e7ef69387e4f9851b9648aa23f1518/dns) and created them. Interestingly, this time I didn't need to add `--namespace=kube-system`, the service and rc appeared without it (not sure why). The rc was created, but the `skydns` container kept on restarting. Here are the logs:

```bash
kubernetes-master ~ # kubectl logs kube-dns-v8-hs8h7 skydns
2015/08/12 08:37:30 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [2]
2015/08/12 08:37:30 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/08/12 08:37:30 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
```

and here's the output of the exec:

```bash
kubernetes-master ~ # kubectl exec busybox -ti nslookup kubernetes
Server:    69.20.0.164
Address 1: 69.20.0.164 cachens1.iad1.rackspace.com

nslookup: can't resolve 'kubernetes'
error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

**Comment by jamiehannaford** [comment]
If I add `; echo ok` to the healthz liveness probe, the skydns logs change to:

```
2015/08/12 09:00:03 skydns: falling back to default configuration, could not read from etcd: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
2015/08/12 09:00:03 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/08/12 09:00:03 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
```

The kube2sky logs are still the same as above.

**Comment by jamiehannaford** [comment]
Pretty sure this is fixed now. I used [the azure files](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides/coreos/azure/addons) and made sure the skydns pointed to their latest version (`skynetservices/skydns:latest`).

**Comment by justingrayston** [comment]
I am currently having the same error. I have been trying for some time to get docker based kubernetes to play nice with DNS.

Raised a [stackoverflow](http://stackoverflow.com/questions/33255676/configure-kube-dns-when-running-kubernetes-via-docker) question before I found this issue.

```
Failed to list *api.Endpoints: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
```

If I go onto the host,and curl the endpoint, the api output is valid JSON.

I am using the instructions from the [docker.md](ttps://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md) and running it locally.

My master and API is accessible via http://0.0.0.0:8080 so no conflict with the pod.

Cluster is started with:

```
# Run etcd
docker run --net=host \
 -d gcr.io/google_containers/etcd:2.0.12 /usr/local/bin/etcd  \
 --addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data

# Run the master
docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:ro \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube:v1.0.6 \
    /hyperkube kubelet --containerized --hostname-override="127.0.0.1" \
     --address="0.0.0.0" --api-servers=http://localhost:8080 \
      --config=/etc/kubernetes/manifests \
      --cluster_dns="10.0.0.10"  --cluster_domain="cluster.local"

# Run the service proxy
docker run -d --net=host --privileged gcr.io/google_containers/hyperkube:v1.0.6 \
 /hyperkube proxy --master=http://127.0.0.1:8080 --v=2
```

skydns-rc.yml is:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v8
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v8
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v8
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v8
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - -domain=cluster.local
        - -kube_master_url=http://0.0.0.0:8080
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=cluster.local.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.

```

and skydns-svc.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP:  "10.0.0.10"
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```

I am pretty much at a loss right now as to why kube2sky is getting the odd output returned from http://0.0.0.0:8080, other services seem ok. If I don't use DNS I can spin up pods and services just fine.

**Comment by justingrayston** [comment]
I have tried all sorts of things now. Using kubernetes/kube2sky instead of cr.io/google_containers/kube2sky:1.11 but then it seems to try and hit v1beta1 api instead of v1, then falls over with a YAML error.

```
 Failed to load services: couldn't get version/kind: YAML error: mapping values are not allowed in this context
```

So, everything I have read seems to suggest some sort of restriction accessing the API, either IP related or [security/firewall related] (https://github.com/kubernetes/kubernetes/issues/11634).

I am running this locally and I am pretty sure IPs are ok. So made the call from the container itself.

```
docker exec  49705c38846a  echo $(curl http://0.0.0.0:8080/api/v1/services?labels=)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   908  100   908    0     0   314k      0 --:--:-- --:--:-- --:--:--  443k
{ "kind": "ServiceList", "apiVersion": "v1", "metadata": { "selfLink": "/api/v1/services", "resourceVersion": "948" }, "items": [ { "metadata": { "name": "kubernetes", "namespace": "default", "selfLink": "/api/v1/namespaces/default/services/kubernetes", "uid": "369a9307-796e-11e5-87de-7a0704d1fdad", "resourceVersion": "6", "creationTimestamp": "2015-10-23T10:09:57Z", "labels": { "component": "apiserver", "provider": "kubernetes" } }, "spec": { "ports": [ { "protocol": "TCP", "port": 443, "targetPort": 443, "nodePort": 0 } ], "clusterIP": "10.0.0.1", "type": "ClusterIP", "sessionAffinity": "None" }, "status": { "loadBalancer": {} } } ] }
```

And endponts too...

```
docker exec  49705c38846a  echo $(curl http://0.0.0.0:8080/api/v1/endpoints?labels=)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   735  100   735    0     0   275k      0 --:--:-- --:--:-- --:--:--  358k
{ "kind": "EndpointsList", "apiVersion": "v1", "metadata": { "selfLink": "/api/v1/endpoints", "resourceVersion": "978" }, "items": [ { "metadata": { "name": "kubernetes", "namespace": "default", "selfLink": "/api/v1/namespaces/default/endpoints/kubernetes", "uid": "369b0f04-796e-11e5-87de-7a0704d1fdad", "resourceVersion": "7", "creationTimestamp": "2015-10-23T10:09:57Z" }, "subsets": [ { "addresses": [ { "ip": "10.0.2.15" } ], "ports": [ { "port": 6443, "protocol": "TCP" } ] } ] } ] }
```

Valid JSON, So why the repeated errors!!!

```
Failed to list *api.Service: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
Failed to list *api.Endpoints: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
```
Which is the correct Image I should be using? Should I open a new ISSUE? Can anyone help?

**Comment by justingrayston** [comment]
UPDATE: Building the latest kube2sky from head, solved the issue with the invalid character. kube2sky no longer throws errors, using the latest skydns, I now get a return on kubernetes.default, but it is not correct, and has incorrect IP.

```
 kubectl exec busybox nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 92.242.132.15 unallocated.barefruit.co.uk
```

**Comment by thockin** [comment]
Is that name (barefruit.co.uk) one of yours or is it totally random?

can you show me `iptables-save` from the node where this resolution is
happening and the /etc/hosts file from your `busybox` where you ran that
exec?

**Comment by justingrayston** [comment]
That domain is I think from the ISP. Nothing to do with me.

Not currently near my laptop, but I will get the info next time I am back
banging my head against this wall.

Will post back here soon, and thanks for responding!

**Comment by justingrayston** [comment]
@thockin I reran this from my office network, and it reverted to a 'could not resolve' error rather than this strange look up. The iptables-save resulted in an empty save. 

Anyway, I think there is something fundamentally going wrong with the way I have it set up.

I resolved the "Failed to list *api.Service: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value" by building my own kube2sky image from head. It then reported it connected to etcd and the API. I don't know if it is doing what it is supposed to do, there is no more log output after start.

So this maybe going off topic and perhaps needs a new issue raising, but before that, I have pushed the set up I am working with to a [repo](https://github.com/justingrayston/kubernetes-docker-dns) and being docker based it should just fire up and replicate what I have. I have spent quite some time changing various things, but this version has minimal changes to what is suggested in the docker.md and dns on the k8s repo.

Some of the things I have noted as possibly problematic I have added to the bottom of the my [README](https://github.com/justingrayston/kubernetes-docker-dns).

I would really appreciate if you have a chance, to please take a look? I am sure it is going to be obvious to someone in the know.

Many thanks!

**Comment by tdeheurles** [comment]
hi,

Following [that similar post](https://gist.github.com/guybrush/47bcd5f4e41a3be102b2), I fix the same issue by adding `kube_master_url` argument to the kube2sky.

```yml
- name: kube2sky
  image: gcr.io/google_containers/kube2sky:1.11
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
  args:
    # command = "/kube2sky"
    - -domain=cluster.local
    - -kube_master_url=http://192.168.1.13:8080
```

If it can help some others ...

**Comment by kcraft** [comment]
@tdeheurles This solved my problem. For some reason the setup script I downloaded assumes that the master is on localhost (or whatever the default is), and that isn't the case for me.

**Comment by thockin** [comment]
The kube_master_url flag should not be needed if you have ServiceAccounts
configured properly.

**Comment by tdeheurles** [comment]
@thockin : which ServiceAccounts are we talking about ? I'm not running on google cloud (using baremetal).

So I suppose you point to that [one](https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/design/service_accounts.md).

Thanks for information. I will have a look. But, for now, the documentation seems more focused on what it is than how to use it no ?

**Comment by thockin** [comment]
I mean kubernetes ServiceAccounts.  Each namespace should have a default
service account which has credentials to access the apiserver.

On Tue, Jan 5, 2016 at 3:20 AM, thibault deheurles <notifications@github.com

**Comment by thockin** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/10265#issuecomment-117267504

**Comment by kcraft** [comment]
I have also confirmed that once the ServiceAccount admission controller is enabled, the kube_master_url option is no longer required.

**Comment by tdeheurles** [comment]
Thanks @thockin & @kcraft.

I have a service account but no secrets. Will have a look to AdmissionController.
I have to look and clean all the config ^^

**Comment by hlamer** [comment]
A hint for guys who faced the same problem: I got the error `Failed to list *api.Service: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value` because of misconfigured kube2sky. My `kube_master_url` was `127.0.0.1:8080`, but `127.0.0.1:8080` is the address of `healthz` in the kube-dns` port. And `healthz` responds with some HTML or XML.
