### ISSUE TITLE
kube-proxy doesn't recover from outdated events

### ISSUE THREAD

**Issue by smreed** [GoogleCloudPlatform/kubernetes#3216]
After running a 0.7.2 cluster in GCE over the weekend, service connections seemed flaky. 

The following lines are recurring in the kube-proxy log on all minions in my cluster. 

    W0105 17:28:25.587865    5051 api.go:188] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/endpoints ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [578/235]) [1577] Reason: Details:<nil> Code:0}

    W0105 00:17:07.886554    5042 api.go:124] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/services ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [348/234]) [1347] Reason: Details:<nil> Code:0}

The indices in the error message do not change over time.

kube-proxy seems to be stuck in an endless loop on this condition and seems to fail to get service and endpoint updates.

**Comment by smreed** [comment]
I brought this up on IRC over the very slow new year holiday, @smarterclayton mentioned this should only really be possible under a high write volume, I presume on the api server or etcd? 

We have certainly been pumping a ton of data through service connections, but I'm not sure anything else we're doing in the cluster would qualify as high write volume.

**Comment by erictune** [comment]
I think this is working as intended.
The kube-proxy "watches" endpoints on the apiserver.
Our internal watching protocol has the apiserver intentionally dropping the connection every few minutes, and clients are supposed to reconnect.

Are you seeing any application-level errors which suggest that the proxy isn't working?

I'd like @lavalamp to confirm my diagnosis, though.  Also, I think we have a related issue discussing how to reduce this warning spew.  Maybe he remembers which issue that was.

**Comment by smreed** [comment]
My logs have these errors once every ~30 seconds each for WatchEndpoints and WatchServices.

I don't think I could prove they are related, but these errors have been highly correlated with application-level issues with connecting to services. My workaround so far has been to `sudo /etc/init.d/kube-proxy restart` on all of my minions. Service connection issues go away, and so do these lines of logging. Could be a red herring, but it seems that this failure is preventing kube-proxy from learning about new endpoints.

**Comment by brendandburns** [comment]
I saw a bug over the weekend, where kube-proxy stopped seeing new services
as well, and when I bounced the server it looked fine.  It definitely
looked like the watch had failed, and wasn't retrying.  I'll take a glance
at the kube-proxy code and try to see if anything jumps out.

--brendan

**Comment by smarterclayton** [comment]
I think I know why this happens now.  It's a bug in our use of etcd combined with the addition of events being written to etcd at a much higher rate than previously.

Basically, etcd has a window (1000 events) that it keeps in memory that you can watch on.  When you start a watch at X, if you get no changes to your watched key in 1000 events, the next time you reconnect you'll be outside the window and you'll get the error.  Our watch loops look like "watch X, when I get an event with version Y set X=Y, if I get disconnected watch again at X".

We need a way to update X even when no events are sent within a window of time.

**Comment by erictune** [comment]
smarterclayton's explanation make sense.  This must be a bug.

**Comment by erictune** [comment]
https://github.com/coreos/fleet/issues/408

**Comment by erictune** [comment]
https://github.com/coreos/etcd/issues/925

**Comment by erictune** [comment]
The same issue will probably affect Kubelet, which has its own watch implementation, as well as the scheduler which has a third one.  Not sure about controller-manager.

**Comment by smarterclayton** [comment]
I think it affects any use of watch - we can mitigate the impact on the server side, but needs a scalable solution.

**Comment by erictune** [comment]
Never mind about scheduler.  That is not watching etcd.

**Comment by erictune** [comment]
pkg/kubelet/config/etcd.go is still probably also affected though.

**Comment by erictune** [comment]
Kubernetes at head does not use etcd for kube-proxy.

**Comment by smarterclayton** [comment]
It is - we just simply pass watch through to etcd.  Anyone who watches something that doesn't change over the period when 1000 writes to etcd will hit this problem.

**Comment by erictune** [comment]
@smreed Does your kube-proxy have a `-master=$BLAH` argument?  I suspect not.  Which cloud provider do you use, or which getting-started-guide did you follow?

**Comment by erictune** [comment]
N.M.  You said you used  0.7.2 cluster in GCE .

**Comment by erictune** [comment]
Ah, so, his kube-proxy is talking to the master, but the master is just passing along the etcd error.

**Comment by smarterclayton** [comment]
Right - and we have no way to pass an updated resource version to the client today, nor a great way to know atomically that we haven't missed a change in the watch stream.  The minimal fix is to treat the error as a reset which requires changes to the root (the master can return an error with resource version zero, but the loop has to handle it).

**Comment by erictune** [comment]
@smarterclayton what does "changes to the root" mean?

**Comment by smarterclayton** [comment]
root = loop, autocomplete fail

**Comment by smarterclayton** [comment]
I don't think that's right for us, because if we were listening at X, got no events in a 1000, then at X+1014 we stopped listening and tried to reconnect, the reconnect happens after X+1014 (let's say X+1020), we would miss events from X+1014 -> X+1020.  

----- Original Message -----

**Comment by brendandburns** [comment]
Yeah, I think the right answer is to do the same thing as at startup.  Do
an initial full-state read, followed by a watch.

--brendan

**Comment by brendandburns** [comment]
This is a high-priority bug, in my mind.  If no one else is working on it,
I'll put together a PR.

--brendan

**Comment by xiang90** [comment]
@smarterclayton Why it is not correct? First you need to recover the state and you need to know the index of the recovery. That is the first get (maybe a recursive get). The index of the recovery is x-etcd-index. Then you watch from x-etcd-inde + 1.

**Comment by smarterclayton** [comment]
Sorry, I didn't state the assumption that in many of the watch cases the list/index call on current state is likely extremely expensive (hundreds or thousands of entries), so keeping the watch going even with no write during the watch window is still a huge performance benefit to the client.

**Comment by xiang90** [comment]
@smarterclayton I think you have to prepare for this kind of failure since the history will never be unlimited. 

Probably it is good to partition the entries into different key space. And maybe etcd can support get last changed index of a key space. If the last change is smaller than the last one you have known, you can bypass a recursive get.

**Comment by smarterclayton** [comment]
Agree history can not be unlimited, and we do design for that case.

A conditional get on a key path prefix would definitely allow us to solve this - we could potentially hide the 401 by issuing a recursive get conditionalized by the last index we saw.

Alternatively, if instead of watch returning 401, if watch could check the keyspace for modifications since that date and simply begin watching, that would also solve our problem elegantly.  Does the store today track that sort of info efficiently (and would it continue to do so under the new store proposal)?

**Comment by a-robinson** [comment]
Not a quick fix, but we could alleviate the frequency of complete reloads by not putting events in the same data store (or same key partition) as the cluster's config info, which should drastically reduce the write rates and help avoid other issues like #2719.

**Comment by lavalamp** [comment]
I'm downgrading this to P1 because I think Brendan's change should allow it to recover.

As far as I understand it, there's two possible further problems here.

A) Suppose a watch times out between a client and apiserver, and then client tries to restart it only to discover that the window has now expired. This can be solved by @smarterclayton's heartbeat idea.

B) Suppose a watch returns a result, and client re-watches but the window has expired. This can only happen if the client is extremely slow to re-watch and is a client problem. Possible solution involves getting our etcd client to use etcd's streaming feature. This really shouldn't be happening, though.

**Comment by smarterclayton** [comment]
Right - hopefully with 0.6.0 we can tweak retention to ridiculous levels (weeks) and this problem goes away for virtually everyone.  I don't know for sure though whether the history traversal will be efficient based on the data structure in the proposed tree.  Something else to raise on the store issue.

----- Original Message -----

**Comment by smreed** [comment]
Running v0.8.0 and still seeing kube-proxy get into this state. The following two messages are being repeated in the logs. The etcd indexes are not changing.

    W0112 16:14:27.835652    3169 api.go:198] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/endpoints ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [10781/5338]) [11780] Reason: Details:<nil> Code:0}
    W0112 16:14:54.260622    3169 api.go:129] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/services ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [10781/3907]) [11780] Reason: Details:<nil> Code:0}
    W0112 16:14:59.510727    3169 api.go:198] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/endpoints ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [10781/5338]) [11780] Reason: Details:<nil> Code:0}
    W0112 16:15:26.213788    3169 api.go:129] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/services ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [10781/3907]) [11780] Reason: Details:<nil> Code:0}

**Comment by brendandburns** [comment]
Hrmph!

I'll look at this today.

Brendan

**Comment by thockin** [comment]
Satnam said he saw it too.

**Comment by lavalamp** [comment]
Hrm. We should make an e2e test that writes a ton of events and then kills a kube-proxy to see if it recovers.

**Comment by jasonkuhrt** [comment]
I believe I am running into this now as well?

```
jasonkuhrt@k8s-littlecloud-1-node-1:~$ tail -f /var/log/kube-proxy.log
I0112 21:38:33.700233    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:33.702284    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j REDIRECT --to-ports 39469]
I0112 21:38:33.704377    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:39469]
I0112 21:38:33.706567    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j REDIRECT --to-ports 47828]
I0112 21:38:33.708635    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:47828]
I0112 21:38:33.710763    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:33.712924    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:33.715008    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:33.717107    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
W0112 21:38:34.568586    4970 api.go:129] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/services ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [549247/505840]) [550246] Reason: Details:<nil> Code:0}
I0112 21:38:38.718486    4970 proxier.go:356] Periodic sync
I0112 21:38:38.718552    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
I0112 21:38:38.720973    4970 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PORTALS-CONTAINER]
I0112 21:38:38.721992    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-HOST -t nat]
I0112 21:38:38.723863    4970 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PORTALS-HOST]
I0112 21:38:38.726041    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:38.728437    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:38.730620    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:38.732805    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:38.736545    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:38.739079    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:38.741661    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:38.743916    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:38.746300    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j REDIRECT --to-ports 57440]
I0112 21:38:38.748592    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j DNAT --to-destination 10.240.130.9:57440]
I0112 21:38:38.750768    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j REDIRECT --to-ports 48850]
I0112 21:38:38.753003    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j DNAT --to-destination 10.240.130.9:48850]
I0112 21:38:38.755190    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:38.757416    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:38.759593    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:38.761680    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:38.764126    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j REDIRECT --to-ports 39469]
I0112 21:38:38.766292    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:39469]
I0112 21:38:38.768394    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j REDIRECT --to-ports 47828]
I0112 21:38:38.770662    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:47828]
I0112 21:38:43.772064    4970 proxier.go:356] Periodic sync
I0112 21:38:43.772135    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
I0112 21:38:43.774695    4970 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PORTALS-CONTAINER]
I0112 21:38:43.775782    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-HOST -t nat]
I0112 21:38:43.780108    4970 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PORTALS-HOST]
I0112 21:38:43.782046    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:43.785111    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:43.787513    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:43.789667    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:43.791771    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j REDIRECT --to-ports 39469]
I0112 21:38:43.794130    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:39469]
I0112 21:38:43.796411    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j REDIRECT --to-ports 47828]
I0112 21:38:43.798607    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:47828]
I0112 21:38:43.801127    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:43.803392    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:43.805615    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:43.808005    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:43.812225    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:43.814765    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:43.817074    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:43.819744    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:43.822035    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j REDIRECT --to-ports 57440]
I0112 21:38:43.824385    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j DNAT --to-destination 10.240.130.9:57440]
I0112 21:38:43.826690    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j REDIRECT --to-ports 48850]
I0112 21:38:43.828962    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j DNAT --to-destination 10.240.130.9:48850]
I0112 21:38:48.830393    4970 proxier.go:356] Periodic sync
I0112 21:38:48.830473    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
I0112 21:38:48.833005    4970 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PORTALS-CONTAINER]
I0112 21:38:48.834050    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-HOST -t nat]
I0112 21:38:48.836307    4970 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PORTALS-HOST]
I0112 21:38:48.838212    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j REDIRECT --to-ports 47828]
I0112 21:38:48.840436    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:47828]
I0112 21:38:48.842809    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:48.845196    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:48.847385    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:48.849509    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:48.851766    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:48.853981    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:48.856512    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:48.858653    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:48.860762    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j REDIRECT --to-ports 57440]
I0112 21:38:48.862973    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j DNAT --to-destination 10.240.130.9:57440]
I0112 21:38:48.865126    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j REDIRECT --to-ports 48850]
I0112 21:38:48.867214    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j DNAT --to-destination 10.240.130.9:48850]
I0112 21:38:48.869298    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:48.871464    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:48.873617    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:48.875865    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:48.880336    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j REDIRECT --to-ports 39469]
I0112 21:38:48.882600    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:39469]
W0112 21:38:52.411648    4970 api.go:198] Got error status on WatchEndpoints channel: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1beta1/endpoints ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cleared (the requested history has been cleared [549303/506612]) [550302] Reason: Details:<nil> Code:0}
I0112 21:38:53.884010    4970 proxier.go:356] Periodic sync
I0112 21:38:53.884084    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-CONTAINER -t nat]
I0112 21:38:53.886471    4970 iptables.go:186] running iptables -C [PREROUTING -t nat -j KUBE-PORTALS-CONTAINER]
I0112 21:38:53.887535    4970 iptables.go:186] running iptables -N [KUBE-PORTALS-HOST -t nat]
I0112 21:38:53.889417    4970 iptables.go:186] running iptables -C [OUTPUT -t nat -j KUBE-PORTALS-HOST]
I0112 21:38:53.891623    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j REDIRECT --to-ports 39469]
I0112 21:38:53.893899    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-master -p tcp -m tcp -d 10.111.249.94/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:39469]
I0112 21:38:53.896088    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j REDIRECT --to-ports 47828]
I0112 21:38:53.898331    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment redis-worker -p tcp -m tcp -d 10.111.242.187/32 --dport 6379 -j DNAT --to-destination 10.240.130.9:47828]
I0112 21:38:53.900777    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:53.902962    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 10.111.250.191/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:53.905136    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j REDIRECT --to-ports 48279]
I0112 21:38:53.907391    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment guestbook -p tcp -m tcp -d 130.211.140.45/32 --dport 3000 -j DNAT --to-destination 10.240.130.9:48279]
I0112 21:38:53.909494    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:53.911874    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 10.111.249.226/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:53.914078    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j REDIRECT --to-ports 55056]
I0112 21:38:53.916416    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment delivery-test -p tcp -m tcp -d 130.211.112.191/32 --dport 9876 -j DNAT --to-destination 10.240.130.9:55056]
I0112 21:38:53.918627    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j REDIRECT --to-ports 57440]
I0112 21:38:53.921227    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes-ro -p tcp -m tcp -d 10.111.251.132/32 --dport 80 -j DNAT --to-destination 10.240.130.9:57440]
I0112 21:38:53.923631    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j REDIRECT --to-ports 48850]
I0112 21:38:53.925894    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment kubernetes -p tcp -m tcp -d 10.111.243.53/32 --dport 443 -j DNAT --to-destination 10.240.130.9:48850]
I0112 21:38:53.928244    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:53.930957    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 10.111.251.250/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
I0112 21:38:53.933319    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-CONTAINER -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j REDIRECT --to-ports 37283]
I0112 21:38:53.935687    4970 iptables.go:186] running iptables -C [KUBE-PORTALS-HOST -t nat -m comment --comment cloud-api-stream -p tcp -m tcp -d 107.178.208.133/32 --dport 7777 -j DNAT --to-destination 10.240.130.9:37283]
```

**Comment by brendandburns** [comment]
Any chance you can patch https://github.com/GoogleCloudPlatform/kubernetes/pull/3410 and try it out?

--brendan

**Comment by jasonkuhrt** [comment]
@brendanburns Hm, well I'm using GKE to manage my clusters. I haven't quite gotten to the point of managing my own deployment yet. Could try if it would really help... : )

Just want to confirm my comment above was indeed related. I went to each node and ran:

```
sudo service kube-proxy restart
```

And then magically all my stress and headaches over the last few days melted away, all my apps were suddenly working!!!

> I brought this up on IRC over the very slow new year holiday, @smarterclayton mentioned this should only really be possible under a high write volume, I presume on the api server or etcd?

Regarding workload size I can say that in my case I think I am doing very very very little. Just launching apps, testing how the API and networking works/feels.

**Comment by smreed** [comment]
@brendandburns it'll take a little work/time but yeah I can do that. I'll report back in a few either way in case something else comes up.

**Comment by brendandburns** [comment]
We're working on writing a test to reproduce this bug, so that we can be
sure we fixed this, this time.

--brendan

**Comment by jasonkuhrt** [comment]
@brendanburns : )

**Comment by smreed** [comment]
@brendandburns would it be valid to just manually copy kube-proxy out to my minions and restart? Or would you rather I do a full cluster tear-down?

**Comment by smreed** [comment]
Nevermind, disks are full on my minions so I'll be tearing it down anyway.

**Comment by brendandburns** [comment]
Is it our fault that your disks are full?

--brendan

**Comment by smreed** [comment]
Ok I'm up and running on a 0.8.0 cluster with the patch from #3410. So far so good.

The full disks are likely due to an issue starting up cadvisor that @vmarmol was helping out with over IRC (no github issue to track AFAIK).

**Comment by smreed** [comment]
Just triggered this by doing a ton of replication controller resizing, saw the "outdated index" messages in the logs and it looks like kube-proxy recovered and my services are still working fine.

cc @brendandburns @jasonkuhrt

**Comment by brendandburns** [comment]
Ok, so you have empirical validation that this seems to fix the problem?

Thanks!
--brendan

**Comment by smreed** [comment]
Correct. I deployed a few hundred pods to get over the 1000-events-in-etcd threshold, saw the error in the kube-proxy log, but only once. 

None of my services are unreachable at this point.

I can see nothing else that indicates that this is still an issue. Thanks for the fix!

**Comment by brendandburns** [comment]
Ok, cool, given that, I'm going to cut a 0.8.1 with this cherry-picked in
and get the release out.  We'll still get a test in place too.

--brendan

**Comment by pires** [comment]
Ah, just when I noticed the bug, I come here and it's fixed. Awesome!!

**Comment by smarterclayton** [comment]
The error message is logged weirdly - fixing that via https://github.com/GoogleCloudPlatform/kubernetes/pull/3608

**Comment by jmreicha** [comment]
I just ran across this the other day.  but I am seeing the error in the `kube-controller-manager` service.  Here is  a sample of the output.

```
Jan 18 15:32:34 aboutme-kube-master kube-controller-manager[865]: E0118 15:32:34.057766     865 replication_controller.go:128] unexpected object: &api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"/api/v1beta1/replicationControllers", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [130635/2384]) [131634]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}
Jan 18 15:32:24 aboutme-kube-master kube-controller-manager[865]: E0118 15:32:24.038972     865 replication_controller.go:128] unexpected object: &api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"/api/v1beta1/replicationControllers", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [130626/2384]) [131625]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}
Jan 18 15:32:14 aboutme-kube-master kube-controller-manager[865]: E0118 15:32:14.016047     865 replication_controller.go:128] unexpected object: &api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"/api/v1beta1/replicationControllers", ResourceVersion:""}, Status:"Failure", Message:"401: The event in requested index is outdated and cleared (the requested history has been cleared [130614/2384]) [131613]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}
```

I can get the behavior to go away temporarily by rebooting the node or restarting the service but it always seems to come back eventually.

**Comment by brendandburns** [comment]
Yeah, we may very well have the same problem in the controller-manager
watch code.  I will check it out.

--brendan

**Comment by brendandburns** [comment]
Closing this as the original issue is fixed.  Opened:

https://github.com/GoogleCloudPlatform/kubernetes/issues/3829

To track the work in replication controller.

**Comment by roackb2** [comment]
I'm not sure what I did wrong but I still get these kind error message widely across my kubernetes components, including kube-proxy, kube-scheduler, kube-controller-manager, kube-apiserver, kubelet.
When observing the logs, it show ups about every 30 seconds.
The error message is as following:

kube-apiserver:
```
Jul 21 13:51:21 dsp-01 kube-apiserver[4276]: E0721 13:51:21.878118    4276 reflector.go:183] watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [365267/365129]) [366266]
Jul 21 14:26:06 dsp-01 kube-apiserver[4276]: E0721 14:26:06.803953    4276 reflector.go:183] watch of *api.ResourceQuota ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [366150/365129]) [367149]
Jul 21 14:29:22 dsp-01 kube-apiserver[4276]: E0721 14:29:22.056964    4276 reflector.go:183] watch of *api.Secret ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [366229/365129]) [367228]
Jul 21 14:34:09 dsp-01 kube-apiserver[4276]: E0721 14:34:09.877753    4276 reflector.go:183] watch of *api.LimitRange ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [366347/365129]) [367346]
Jul 21 14:35:01 dsp-01 kube-apiserver[4276]: E0721 14:35:01.630514    4276 reflector.go:183] watch of *api.ServiceAccount ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [366368/365129]) [367367]
Jul 21 14:36:38 dsp-01 kube-apiserver[4276]: E0721 14:36:38.057345    4276 reflector.go:183] watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [366407/365129]) [367406]
Jul 21 14:44:57 dsp-01 kube-apiserver[4276]: E0721 14:44:57.302124    4276 reflector.go:183] watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [366611/366267]) [367610]
Jul 21 15:26:13 dsp-01 kube-apiserver[4276]: E0721 15:26:13.253458    4276 reflector.go:183] watch of *api.Secret ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [367622/367229]) [368621]
Jul 21 15:28:18 dsp-01 kube-apiserver[4276]: E0721 15:28:18.727808    4276 reflector.go:183] watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [367672/367407]) [368671]
Jul 21 15:30:19 dsp-01 kube-apiserver[4276]: E0721 15:30:19.093392    4276 reflector.go:183] watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [367722/367613]) [368721]
Jul 21 15:32:14 dsp-01 kube-apiserver[4276]: E0721 15:32:14.809743    4276 reflector.go:183] watch of *api.LimitRange ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [367769/367348]) [368768]
```
other components are similar, if needed I can provide their error messages later.
I'm running kubernetes 1.0, to avoid some bugs at version 0.19, the accurate version info is
```
Client Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-15-g2c27b1fa64f4e7", GitCommit:"2c27b1fa64f4e70f04575d1b217494f49332390e", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-15-g2c27b1fa64f4e7", GitCommit:"2c27b1fa64f4e70f04575d1b217494f49332390e", GitTreeState:"clean"}
```
I yum installed kubernets from [here](http://cbs.centos.org/kojifiles/packages/kubernetes/0.19.0/0.4.gita8269e3.el7/)

System info:
```
[root@dsp-01 ~]# uname -a
Linux dsp-01 3.10.63-11.el7.x86_64 #1 SMP Tue Apr 7 16:47:43 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Tried my best to solve the problem on my own but got no progress, if I should provide any other information or investigate something please let me know.

**Comment by lavalamp** [comment]
Seeing this periodically every five minutes or so is not actually a
problem; the system will just list and watch again. We are working on some
changes that will make this much less frequent. But until then, don't worry
about this unless it's happening like once a second.

**Comment by dalanlan** [comment]
What if i owed a cluster which is completely free of this problem while another suffers?

**Comment by roackb2** [comment]
So seeing this message is actually ok?
If so, I suggest to mark it as warn instead of error
As a user, I'll try to clear out all error messages in case unknown failure afterwards.
Thanks for your reply.

**Comment by lavalamp** [comment]
I expect this to be more common in a more heavily loaded cluster. Does that
explain it?

**Comment by lavalamp** [comment]
Yeah, we should change this.

**Comment by dalanlan** [comment]
Nope, exactly the opposite, which make it much odder to me. @lavalamp 
(Different authentication configuration,tough.)

**Comment by lavalamp** [comment]
Are both clusters running the same version?

**Comment by dalanlan** [comment]
The one suffers v1.0.1, while the healthy one v0.18.2.
