### ISSUE TITLE
apiserver develops a dangling pod w/o name

### ISSUE THREAD

**Issue by alex-mohr** [GoogleCloudPlatform/kubernetes#3950]
@davidopp After creating and deleting a bunch of unique-named pause pods, the master ended up with a zombie? pod entry:

> % gcloud preview container pods --cluster=${PROJECT} list
> POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                                                               LABELS              STATUS
>                                                                                 k8s-prod5-node-1.c.mohr-instance-manager.internal/130.211.164.97   <none>              Unknown

Here's the 1 node's view:
> node-1% docker ps
> CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS                      NAMES
> 9558807f5bd4        kubernetes/pause:go     "/pause"              About an hour ago   Up About an hour                               k8s_pause-pod-a3c58ab1.fd6cd67a_pause-pod-a3c58ab1.default.etcd_2896301e-a7f7-11e4-a2ec-42010af0de1f_70214b24   
> f4a4f659dc37        kubernetes/pause:go     "/pause"              About an hour ago   Up About an hour    0.0.0.0:15670->15670/tcp   k8s_net.e468acc9_pause-pod-a3c58ab1.default.etcd_2896301e-a7f7-11e4-a2ec-42010af0de1f_286dfd30                  
> 3eb6b397cbfe        google/cadvisor:0.8.0   "/usr/bin/cadvisor"   About an hour ago   Up About an hour                               k8s_cadvisor.54c805f9_cadvisor-agent.default.file_cadvisormanifes12uqn2ohido76855gdecd9roadm7l0_a7d38033        
> 4e76f64b66ff        kubernetes/pause:go     "/pause"              About an hour ago   Up About an hour    0.0.0.0:4194->8080/tcp     k8s_net.1509ae25_cadvisor-agent.default.file_cadvisormanifes12uqn2ohido76855gdecd9roadm7l0_706122ee             

And etcd's db dump on the master VM:
% curl -s -L http://127.0.0.1:4001/v2/keys/registry/pods/default | python -m json.tool
{
    "action": "get", 
    "node": {
        "createdIndex": 26, 
        "dir": true, 
        "key": "/registry/pods/default", 
        "modifiedIndex": 26, 
        "nodes": [
            {
                "createdIndex": 2266, 
                "key": "/registry/pods/default/pause-pod-3da11ec1", 
                "modifiedIndex": 2266, 
                "value": "{\"kind\":\"Pod\",\"creationTimestamp\":null,\"apiVersion\":\"v1beta1\",\"desiredState\":{\"manifest\":{\"version\":\"v1beta2\",\"id\":\"\",\"volumes\":null,\"containers\":null,\"restartPolicy\":{}}},\"currentState\":{\"manifest\":{\"version\":\"\",\"id\":\"\",\"volumes\":null,\"containers\":null,\"restartPolicy\":{}},\"host\":\"k8s-prod5-node-1.c.mohr-instance-manager.internal\"}}"
            }
        ]
    }
}

Part of long-running masters: #3936

**Comment by alex-mohr** [comment]
FWIW, apparently not just a one-off.  There are now 3 such entries after more pod creation/deletion.

**Comment by erictune** [comment]
I saw a user complain about this about 2 weeks ago.  So, it is probably not
a newly introduced problem.

**Comment by brendandburns** [comment]
Yeah, I've seen this occasionally.  We should dig in and sort out what the issue is.  @alex-mohr sounds like you have a decent repro?

**Comment by alex-mohr** [comment]
Repro would presumably happen via script in #3936?

**Comment by yujuhong** [comment]
I haven't been able to reproduce this issue, so I'd like to get some dumb questions out first :)

Here is what I did:
- Create a cluster with one node. 
`gcloud preview container clusters create onenode --num-nodes 1 --machine-type n1-standard-1`
- Launch 3 processes running the script from #3936

So far I haven't seen any dangling pods, but most of the pause-pods are stuck at pending state and only one is running at any given time. This doesn't seem right because multiple pods should be able to be scheduled on the node at the same time. Did I miss something?

**Comment by alex-mohr** [comment]
Thanks for taking a look!

Your cluster create looks the same.

The script from #3936 uses a fixed --port=3009, so running 3 unchanged copies will result in 3 pods all competing for that port on the host, resulting in at most 1 being scheduled at a time with the others pending.  You'd need to use different ports for each.

**Comment by alex-mohr** [comment]
FWIW, I updated my script for more parallelization: http://pastebin.com/7ZBcXX83
It picks random ports and launches N=20 pause pods at a time.

I setup a fresh cluster from 0.10.0 with 3 nodes and re-ran that pastebin script.  After 15 iterations, it got stuck because there was an error creating 1 pod:
ERROR: F0205 13:55:36.913799    7921 create.go:78] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

After aborting, there were ~15 zombie pods this time:
gcloud preview container pods --cluster=prod10a list
POD                 IP                  CONTAINER(S)        IMAGE(S)                           HOST                                                                 LABELS              STATUS
                                                                                               k8s-prod10a-node-2.c.mohr-instance-manager.internal/104.154.49.156   <none>              Unknown
                                                                                               k8s-prod10a-node-2.c.mohr-instance-manager.internal/104.154.49.156   <none>              Unknown
[etc]

**Comment by yujuhong** [comment]
Oops, yes, you were right about the port number. 

I modified the script and used 5 processes with 30 iteration each. I've still not encountered the dangling pod problem, even though there seem to be some other issues.

- Deleting a pod sometimes fails. Not sure if it's user's responsibility to retry, but it could be.
- After running for a while, scheduling (or status update) became extremely slow. The pods were stuck at pending for > 3 minutes before changing to running.

@alex-mohr, how many concurrent processes were you running and how long did they run for you to produce the dangling pods?

**Comment by yujuhong** [comment]
I missed your new comment before posting mine. I will try the new script and report back. Thanks!

**Comment by alex-mohr** [comment]
@yujuhong 2 processes this time and it took a couple of minutes.

**Comment by yujuhong** [comment]
FYI, I was able to reproduce the issue after a longer run. I will start digging around and see what the root cause is.

**Comment by bgrant0607** [comment]
This is a long-standing problem. See, for instance, #1892.

**Comment by yujuhong** [comment]
Here is an update with some more information but much progress:

 * I reproduced the issue on the GCE cluster and changed the logging level to 7.
 * As mentioned in #3939, `kube-apiserver.log` encounters etcd errors periodically when creating pods `E0209 18:40:45.937988    4964 errors.go:52] apiserver received an error that is not an api.Status: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]`
  * The phantom pods were created, scheduled, run, and killed as observed from the scheduler and the apiserver log. After the pod has been killed, it somehow turned into a phantom pod.
  * Pods frequently failed (exit code 2) and were restarted/recreated. When I turned off the automatic restart, many pods ended up in the failed state before any phantom pod appeared.
  * I have seen a pod being scheduled after the API server supposed killed the pod.

**Comment by yujuhong** [comment]
I suspect this is an etcd issue. As mentioned in the previous comment, pod was still being scheduled after the pod has supposedly been deleted. Here is a snippet of such a pod:

```
kube-scheduler.log:I0210 01:16:41.316617    5233 factory.go:136] glog.v2 --> About to try and schedule pod pause-pod-1616b21
kube-scheduler.log:I0210 01:16:41.316668    5233 scheduler.go:71] Attempting to schedule: &{{ } {pause-pod-1616b21  default /api/v1beta1/pods/pause-pod-1616b21 78111d6c-b0c2-11e4-a4b9-42010af0b14c 4043 2015-02-10 01:16:41 +0000 UTC map[name:pause-pod-1616b21] map[]} {[] [{pause-container kubernetes/pause []  [{ 12490 12490 TCP }] [] {map[]} [] <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0xaec2a0 <nil> <nil>} ClusterFirst map[] } {Pending     map[]}}
kube-scheduler.log:I0210 01:16:41.317215    5233 priorities.go:67] pause-pod-1616b21 -> kubernetes-minion-1.c.cloud-containers-yjhong.internal: Least Requested Priority, AbsoluteRequested: (0, 0) / (1000, 4026531840) Score: (10, 10)
kube-scheduler.log:I0210 01:16:41.317244    5233 priorities.go:67] pause-pod-1616b21 -> kubernetes-minion-2.c.cloud-containers-yjhong.internal: Least Requested Priority, AbsoluteRequested: (0, 0) / (1000, 4026531840) Score: (10, 10)
kube-scheduler.log:I0210 01:16:41.317622    5233 factory.go:274] Attempting to bind pause-pod-1616b21 to kubernetes-minion-1.c.cloud-containers-yjhong.internal
kube-scheduler.log:I0210 01:18:01.785769    5233 factory.go:136] glog.v2 --> About to try and schedule pod pause-pod-1616b21
kube-scheduler.log:I0210 01:18:01.785796    5233 scheduler.go:71] Attempting to schedule: &{{ } {pause-pod-1616b21  default /api/v1beta1/pods/pause-pod-1616b21?namespace=default 78111d6c-b0c2-11e4-a4b9-42010af0b14c 4022 2015-02-10 01:16:41 +0000 UTC map[name:pause-pod-1616b21] map[]} {[] [{pause-container kubernetes/pause []  [{ 12490 12490 TCP }] [] {map[]} [] <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0xaec2a0 <nil> <nil>} ClusterFirst map[] } {Running   130.211.162.42 10.244.0.180 map[POD:{{<nil> 0xc2082c3ae0 <nil>} 0 10.244.0.180 kubernetes/pause:latest docker://6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27 docker://67034a7b2350dd1dd56605691dfd8667431a5affb3dde4ce40ba4bd33529a58b} pause-container:{{<nil> 0xc2082c3ca0 <nil>} 0  kubernetes/pause docker://6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27 docker://ef2ccf0757a397928b09feff5f0dbe4de865ac5c4a450eb1552b28f356a405a9}]}}
kube-scheduler.log:I0210 01:18:01.786140    5233 priorities.go:67] pause-pod-1616b21 -> kubernetes-minion-2.c.cloud-containers-yjhong.internal: Least Requested Priority, AbsoluteRequested: (0, 0) / (1000, 4026531840) Score: (10, 10)
kube-scheduler.log:I0210 01:18:01.786187    5233 priorities.go:67] pause-pod-1616b21 -> kubernetes-minion-1.c.cloud-containers-yjhong.internal: Least Requested Priority, AbsoluteRequested: (0, 0) / (1000, 4026531840) Score: (10, 10)
kube-scheduler.log:I0210 01:18:01.786267    5233 factory.go:274] Attempting to bind pause-pod-1616b21 to kubernetes-minion-2.c.cloud-containers-yjhong.internal
kube-apiserver.log:I0210 01:20:56.586529    5045 handlers.go:108] GET /api/v1beta1/pods/pause-pod-1616b21?namespace=default: (2.512143ms) 200
kube-apiserver.log:I0210 01:20:56.798084    5045 handlers.go:108] DELETE /api/v1beta1/pods/pause-pod-1616b21?namespace=default: (168.413613ms) 200
kube-scheduler.log:I0210 01:32:01.628871    5233 factory.go:136] glog.v2 --> About to try and schedule pod pause-pod-1616b21
kube-scheduler.log:I0210 01:32:01.628893    5233 scheduler.go:71] Attempting to schedule: &{{ } {pause-pod-1616b21  default /api/v1beta1/pods/pause-pod-1616b21?namespace=default 78111d6c-b0c2-11e4-a4b9-42010af0b14c 4022 2015-02-10 01:16:41 +0000 UTC map[name:pause-pod-1616b21] map[]} {[] [{pause-container kubernetes/pause []  [{ 12490 12490 TCP }] [] {map[]} [] <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0xaec2a0 <nil> <nil>} ClusterFirst map[] } {Unknown     map[]}}
kube-scheduler.log:I0210 01:32:01.629157    5233 priorities.go:67] pause-pod-1616b21 -> kubernetes-minion-1.c.cloud-containers-yjhong.internal: Least Requested Priority, AbsoluteRequested: (0, 0) / (1000, 4026531840) Score: (10, 10)
kube-scheduler.log:I0210 01:32:01.629259    5233 priorities.go:67] pause-pod-1616b21 -> kubernetes-minion-2.c.cloud-containers-yjhong.internal: Least Requested Priority, AbsoluteRequested: (0, 0) / (1000, 4026531840) Score: (10, 10)
kube-scheduler.log:I0210 01:32:01.629317    5233 factory.go:274] Attempting to bind pause-pod-1616b21 to kubernetes-minion-2.c.cloud-containers-yjhong.internal
```

Note that the delete request returned OK (200).
```DELETE /api/v1beta1/pods/pause-pod-1616b21?namespace=default: (168.413613ms) 200```
However, the key lives and scheduler even attempted to schedule it again (while the pod was in the unknown status).

The content of the key/pod in etcd showed that most of the content has been cleared.
```
etcdctl --peers=10.240.177.76:4001 get registry/pods/default/pause-pod-1616b21
{"kind":"Pod","creationTimestamp":null,"apiVersion":"v1beta1","desiredState":{"manifest":{"version":"v1beta2","id":"","volumes":null,"containers":null,"restartPolicy":{}}},"currentState":{"manifest":{"version":"","id":"","volumes":null,"containers":null,"restartPolicy":{}},"host":"kubernetes-minion-2.c.cloud-containers-yjhong.internal"}}
```

I may add a check after the deletion to make sure that the key **was deleted** when etcd claimed to have done so.

**Comment by yujuhong** [comment]
Okay, I think I've narrowed it down to a race condition between deleting and scheduling a pod. The series of events happened in the following order according to the timestamps in the logs.

1. The script sends a request to create Pod X
2. Pod X is created, scheduled, and run on one of the minions.
3. The script sends a request to delete Pod X
4. The pod entry (registry/pods/default/X) in the etcd is deleted.
5. The atomic update to BoundPods fails because Pod X is nowhere to be found (cause unknown).
6. Scheduler tries to schedule the Pod X again (I suspect the scheduler caches the pods so the entries were stale?)
7. Scheduler wants to bind Pod X to a new host. One of the binding steps involves calling `setPodHostTo()` to perform an atomic update on X. Because Pod X does not exist, a new key entry with mostly empty content is created.

I confirmed that the pod deletion in step (4) was successful by adding code to retrieve the deleted entry immediately after the deletion. For step (7), the implicit creation is done in AtomicUpdate() in etcd_tools.go (comment: `// First time this key has been used, try creating new value.`).

What remains unknown is that (a) why scheduler was looking at stale pod entries and (b) why Pod X was not in the BoundPods at the time of the deletion. The former seems like the major issue, while the later a minor one.

**Comment by yujuhong** [comment]
cc @dchen1107

**Comment by dchen1107** [comment]
Cool, thanks for investigation, and result confirms the hyperthesis we had yesterday. cc/ @davidopp about the scheduler.

**Comment by yujuhong** [comment]
It is strange that the scheduler wanted to schedule the pod again. The pod had been running for a while at that time and the pod entry couldn't be that stale (?). I am going to make a wild guess and say that this may be related to #4188, in which the comments suggest that a running pod may flip to pending intermittently. I am ready to be struck down again though... :|

**Comment by yujuhong** [comment]
At the least, the binding should not happen if the pod entry does not exist. I will write up a PR for that.

**Comment by smarterclayton** [comment]
I found a huge bug in update and delete pods, where bindings of same named pods in different namespaces have the wrong bound pod update applied.  That may overlap with this fix, I'm going to send that in after lunch.

**Comment by yujuhong** [comment]
PR #4326 is supposed to fix the main symptom -- phantom/dangling pods, which are placeholder pod keys created after the pod has been deleted. The flipping between pending/running status is discussed and to be fixed in #4188.

The BoundPod update failure needs more investigation. In my tests, all pods use the same namespace, so they should not be affected by the bug @smarterclayton posted above.

**Comment by smarterclayton** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/4329 fixes the cross namespace issue.

----- Original Message -----

**Comment by yujuhong** [comment]
I am going to close this issue for now, since the main symptom is gone as far as I know. Please re-open it if you can reproduce the issue.
