### ISSUE TITLE
Update Debugging FAQ to refer to kubectl

### ISSUE THREAD

**Issue by DreadPirateShawn** [GoogleCloudPlatform/kubernetes#4782]
The "Debugging FAQ" page still refers to `kubecfg list events` rather than `kubectl get events`.
https://github.com/GoogleCloudPlatform/kubernetes/wiki/Debugging-FAQ

Related to #2144.

**Comment by vishh** [comment]
I think this has been fixed.

**Comment by DreadPirateShawn** [comment]
Only partially fixed -- `kubecfg` was changed to `kubectl`, however now it's an invalid command -- `cluster/kubectl.sh list events` doesn't work, the "list" also needs to be changed to "get".

**Comment by DreadPirateShawn** [comment]
```
$ cluster/kubectl.sh list events
KUBE_MASTER_IP: 10.245.1.2
Running: cluster/../cluster/vagrant/../../_output/dockerized/bin/darwin/amd64/kubectl --auth-path=/Users/sfalknerhorine/.kubernetes_vagrant_auth list events

Usage: 
  kubectl [flags]
  kubectl [command]

Available Commands: 
  version                                                                                                                                                           Print version of client and server
  proxy                                                                                                                                                             Run a proxy to the Kubernetes API server
  get [(-o|--output=)json|yaml|...] <resource> [<id>]                                                                                                               Display one or many resources
  describe <resource> <id>                                                                                                                                          Show details of a specific resource
  create -f filename                                                                                                                                                Create a resource by filename or stdin
  update -f filename                                                                                                                                                Update a resource by filename or stdin
  delete ([-f filename] | (<resource> [(<id> | -l <label>)]                                                                                                         Delete a resource by filename, stdin or resource and id
  config <subcommand>                                                                                                                                               config modifies .kubeconfig files
  namespace [<namespace>]                                                                                                                                           SUPERCEDED: Set and view the current Kubernetes namespace
  log [-f] <pod> [<container>]                                                                                                                                      Print the logs for a container in a pod.
  rollingupdate <old-controller-name> -f <new-controller.json>                                                                                                      Perform a rolling update of the given ReplicationController
  resize [--resource-version=<version>] [--current-replicas=<count>] --replicas=<count> <resource> <id>                                                             Set a new size for a resizable resource (currently only Replication Controllers)
  run-container <name> --image=<image> [--port=<port>] [--replicas=replicas] [--dry-run=<bool>] [--overrides=<inline-json>]                                         Run a particular image on the cluster.
  stop <resource> <id>                                                                                                                                              Gracefully shutdown a resource
  expose <name> --port=<port> [--protocol=TCP|UDP] [--container-port=<number-or-name>] [--service-name=<name>] [--public-ip=<ip>] [--create-external-load-balancer] Take a replicated application and expose it as Kubernetes Service
  help [command]                                                                                                                                                    Help about any command

 Available Flags:
      --alsologtostderr=false: log to standard error as well as files
      --api-version="": The API version to use when talking to the server
  -a, --auth-path="": Path to the auth info file. If missing, prompt the user. Only used if using https.
      --certificate-authority="": Path to a cert. file for the certificate authority.
      --client-certificate="": Path to a client key file for TLS.
      --client-key="": Path to a client key file for TLS.
      --cluster="": The name of the kubeconfig cluster to use
      --context="": The name of the kubeconfig context to use
  -h, --help=false: help for kubectl
      --insecure-skip-tls-verify=false: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.
      --kubeconfig="": Path to the kubeconfig file to use for CLI requests.
      --log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
      --log_dir=: If non-empty, write log files in this directory
      --log_flush_frequency=5s: Maximum number of seconds between log flushes
      --logtostderr=true: log to standard error instead of files
      --match-server-version=false: Require server version to match client version
      --namespace="": If present, the namespace scope for this CLI request.
  -s, --server="": The address of the Kubernetes API server
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --token="": Bearer token for authentication to the API server.
      --user="": The name of the kubeconfig user to use
      --v=0: log level for V logs
      --validate=false: If true, use a schema to validate the input before sending it
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging

Use "kubectl help [command]" for more information about that command.
Error: unknown command "--auth-path=/Users/sfalknerhorine/.kubernetes_vagrant_auth"
Run 'help' for usage.

kubectl: invalid command [`--auth-path=/Users/sfalknerhorine/.kubernetes_vagrant_auth` `list` `events`]
Run 'kubectl help' for usage
```

**Comment by DreadPirateShawn** [comment]
```
$ cluster/kubectl.sh get events | tail
KUBE_MASTER_IP: 10.245.1.2
Running: cluster/../cluster/vagrant/../../_output/dockerized/bin/darwin/amd64/kubectl --auth-path=/Users/sfalknerhorine/.kubernetes_vagrant_auth get events
Tue, 24 Feb 2015 20:16:01 +0000   frontend-controller-nyxxv   BoundPod            implicitly required container POD   killing             {kubelet 10.245.1.5}   Killing a62e9073da6cb017d68d57d621fd66f91fb1847923edb9af3f6fe0a3df4570db - /k8s_POD.1f25df3e_frontend-controller-nyxxv.default.api_60b535ac-b211-11e4-830f-0800279696e1_420b0c52
Tue, 24 Feb 2015 20:16:01 +0000   frontend-controller-nyxxv   BoundPod            spec.containers{php-redis}          killing             {kubelet 10.245.1.5}   Killing d318aa37c8eca56b7dcebac7656a6112a9da82a8b9141c0aab584629eacb883c - /k8s_php-redis.83c3fa7c_frontend-controller-nyxxv.default.api_60b535ac-b211-11e4-830f-0800279696e1_556451a9
Tue, 24 Feb 2015 20:16:03 +0000   frontend-controller-nyxxv   BoundPod            spec.containers{php-redis}          created             {kubelet 10.245.1.5}   Created with docker id 975113e8113f20324797117f5c99f60b00e60e72bb1eb3aea279138bc31f918c
Tue, 24 Feb 2015 20:16:03 +0000   frontend-controller-nyxxv   BoundPod            spec.containers{php-redis}          failed              {kubelet 10.245.1.5}   Failed to start with docker id 975113e8113f20324797117f5c99f60b00e60e72bb1eb3aea279138bc31f918c with error: API error (500): Cannot start container 975113e8113f20324797117f5c99f60b00e60e72bb1eb3aea279138bc31f918c: cannot join network of a non running container: a62e9073da6cb017d68d57d621fd66f91fb1847923edb9af3f6fe0a3df4570db

Tue, 24 Feb 2015 20:16:11 +0000   frontend-controller-nyxxv   BoundPod            implicitly required container POD   created             {kubelet 10.245.1.5}   Created with docker id 0ee1064ff7ba55489841c6c991071dfd9bee47c24289db891818953913914adb
Tue, 24 Feb 2015 20:16:11 +0000   frontend-controller-nyxxv   BoundPod            implicitly required container POD   pulled              {kubelet 10.245.1.5}   Successfully pulled image "kubernetes/pause:latest"
Tue, 24 Feb 2015 20:16:12 +0000   frontend-controller-nyxxv   BoundPod            implicitly required container POD   started             {kubelet 10.245.1.5}   Started with docker id 0ee1064ff7ba55489841c6c991071dfd9bee47c24289db891818953913914adb
Tue, 24 Feb 2015 20:16:14 +0000   frontend-controller-nyxxv   BoundPod            spec.containers{php-redis}          created             {kubelet 10.245.1.5}   Created with docker id 330739cc7eaacb88f6f5ffc47fae7d685f04537597f028e882b648dcc7802a6b
Tue, 24 Feb 2015 20:16:14 +0000   frontend-controller-nyxxv   BoundPod            spec.containers{php-redis}          started             {kubelet 10.245.1.5}   Started with docker id 330739cc7eaacb88f6f5ffc47fae7d685f04537597f028e882b648dcc7802a6b
```

**Comment by bgrant0607** [comment]
Appears to have been fixed.

**Comment by DreadPirateShawn** [comment]
Is the fix not deployed yet?

I just loaded https://github.com/GoogleCloudPlatform/kubernetes/wiki/Debugging-FAQ in a fresh browser to ensure no caching, and it still says:

```
You can see what's happening in Kubernetes with cluster/kubectl.sh list events.
```

However, that command does not exist -- the old command is `cluster/kubecfg.sh list events` and the new command is `cluster/kubectl.sh get events`. The current command on the page still appears to be broken.

**Comment by DreadPirateShawn** [comment]
Since "kubecfg" was indeed changed to "kubectl", I understand why this ticket was closed... However, the command is now invalid/broken, which definitely still needs to be fixed.

I've filed #4847 for clarity (and additional visibility, since the debugging page currently contains a broken command).

**Comment by bgrant0607** [comment]
I can only find 2 instances, and they have both been fixed.
