### ISSUE TITLE
Scheduling plateaus due to POD killing 

### ISSUE THREAD

**Issue by timothysc** [GoogleCloudPlatform/kubernetes#5654]
Following the same test outlined in #5650, you can trace the events and will notice that one of the major reasons why the ramp curve for startup is non-linear, and has plateaus, is due to the pod killing done by the controllers, giving incorrect feedback into the system.  

Using the soak test that @jayunit100 you can see a graphical representation of this. 

**Related Issues:**
https://github.com/GoogleCloudPlatform/kubernetes/issues/3954
https://github.com/GoogleCloudPlatform/kubernetes/issues/3952

**Expected Results:** 
No pod killing on ramp up.

**Comment by lavalamp** [comment]
Why are controllers killing pods? That's probably not the root cause. (More probable: too many/conflicting pods assigned to a single host, kubelet sets pods to failed. #5446 should greatly reduce this problem though.)

Alternatively, the controller is reacting too fast, starting N pods, then noticing only M are running and starting another N-M pods, then later killing N-M pods. This would be a true controller bug; it should count pods that are going to start running even if they haven't started yet. But I don't think we have this bug?

I think it's P1 to figure out what's going on.

**Comment by timothysc** [comment]
@lavalamp the merge for #5446 was done 3 days ago, this test was from tip of last night.  

Correction: "is due to the pod killing done by the controllers" - I don't know exactly who is doing the killing, that is a supposition on my part ^

**Comment by davidopp** [comment]
which is "the soak test that @jayunit100" that you're referring to? #5447 ?

**Comment by jayunit100** [comment]
thats a way you can visualize this - when the job starts, the throughput is constant for a long time, and then jumps.   A screenshot of the graphing part of the app is here (the plateau is not included in this timeslice) https://cloud.githubusercontent.com/assets/826111/6604156/0091d88a-c7fd-11e4-983a-c414e92220cd.jpg.  in any case you can also pol the number of pods that are running 

```
for i in 1 to 150; do
    kubectl get pods | grep blah | wc -l  ; done
``
and  invariably get something like this (if RC=is 5)

```
3
3
3
3
3
3
3
3
3
3
8
8
8
8
8
8
8
8
8
8
15
15
...

```

**Comment by wojtek-t** [comment]
I observed a very similar behavior - I looked a bit deeper into it and basically, all the pods get pending pretty quickly and it took quite a lot of time to start them and report back to apiserver that they are started.

cc @fgrzadkowski 
i think that #5714 might help, but we also need to look deeper into what takes time when starting pods.

**Comment by quinton-hoole** [comment]
+satnam@google.com FYI

**Comment by lavalamp** [comment]
I am unable to repro this. I modified contrib/for-tests/network-tester/rc.json to make 150 pods and ran a loop getting the number of running pods every three seconds. Output below. It seems to monotonically and quickly make progress.

```
10
current-context: "crested-analogy-671_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl get pods
17
current-context: "crested-analogy-671_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl get pods
20
current-context: "crested-analogy-671_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl get pods
74
current-context: "crested-analogy-671_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl get pods
95
current-context: "crested-analogy-671_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl get pods
126
current-context: "crested-analogy-671_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl get pods
139
current-context: "crested-analogy-671_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl get pods
160
```

**Comment by timothysc** [comment]
The repro is mentioned in #5650, and we re-created last friday.

**Comment by davidopp** [comment]
@timothysc Can you check to see if this problem is now fixed, and if so, close the issue?

**Comment by timothysc** [comment]
@davidopp yes, we'll run have a test run this afternoon.

**Comment by wojtek-t** [comment]
@timothysc Did you run this test - I think this was caused by #6059 and I think it should be fixed now.

**Comment by timothysc** [comment]
@wojtek-t  yes we can close this issue.  However I'm still deep into e2e to try and prevent future regressions. 

fwiw, we still see lumps in draining a pool, but there are so many tickets around that area I'll wait to file a new one.
