### ISSUE TITLE
Error scheduling controller: PodFitsPorts

### ISSUE THREAD

**Issue by sumkincpp** [GoogleCloudPlatform/kubernetes#5798]
With some of the recent master branches Kubernetes cannot schedule underlying pod with `PodFitsPorts` error :
```
~$ kubectl get events | tail
Mon, 23 Mar 2015 20:57:08 +0300   Mon, 23 Mar 2015 20:57:08 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc208202f10 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc208202f80 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc208202ff0 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc208203060 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc2082030d0 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc208203140 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsResources
Mon, 23 Mar 2015 20:57:24 +0300   Mon, 23 Mar 2015 20:57:24 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc2081d8b00 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc2081d8b80 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc2081d8c10 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc2081d8cd0 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc2081d8e70 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc2081d8f20 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
Mon, 23 Mar 2015 20:57:56 +0300   Mon, 23 Mar 2015 20:57:56 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc208170700 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc208170790 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc208170860 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc208170920 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc208170990 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc208170a00 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
Mon, 23 Mar 2015 20:58:56 +0300   Mon, 23 Mar 2015 20:58:56 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc2080e2540 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc2080e25b0 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc2080e2620 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc2080e2690 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc2080e2700 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc2080e2770 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsResources
Mon, 23 Mar 2015 20:58:57 +0300   Mon, 23 Mar 2015 20:58:57 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc20818aec0 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc20818af50 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc20818afc0 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc20818b030 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc20818b0a0 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc20818b110 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
Mon, 23 Mar 2015 20:58:59 +0300   Mon, 23 Mar 2015 20:58:59 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc2081d9030 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc2081d90e0 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc2081d9150 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc2081d91c0 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc2081d9230 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc2081d92a0 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[memory:{419430400 BinarySI} cpu:{1.000 DecimalSI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
Mon, 23 Mar 2015 20:59:03 +0300   Mon, 23 Mar 2015 20:59:03 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc208203140 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc2082031b0 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc208203220 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc208203290 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc208203300 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc208203370 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
Mon, 23 Mar 2015 20:59:11 +0300   Mon, 23 Mar 2015 20:59:11 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc208158140 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc2081581b0 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc208158220 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc2081582a0 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc208158320 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc208158390 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
Mon, 23 Mar 2015 20:59:27 +0300   Mon, 23 Mar 2015 20:59:27 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc2081974e0 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc208197550 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc2081975c0 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc208197630 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc2081976a0 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc208197710 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
Mon, 23 Mar 2015 20:59:59 +0300   Mon, 23 Mar 2015 20:59:59 +0300   1                   verse-controller    Pod                                     failedScheduling    {scheduler }        Error scheduling: failed to find fit for pod: {{ } {verse-controller  default /api/v1beta1/pods/verse-controller?namespace=default 20b0fce7-d185-11e4-aab6-0a0a07552556 336958 2015-03-23 20:50:43 +0300 MSK <nil> map[name:frontend] map[]} {[{www-data {0xc208158c30 <nil> <nil> <nil> <nil> <nil>}} {ssl-certificates {0xc208158ca0 <nil> <nil> <nil> <nil> <nil>}} {log-data {0xc208158d10 <nil> <nil> <nil> <nil> <nil>}} {sites-enabled-data {0xc208158d80 <nil> <nil> <nil> <nil> <nil>}} {mysql {0xc208158df0 <nil> <nil> <nil> <nil> <nil>}} {scripts {0xc208158e60 <nil> <nil> <nil> <nil> <nil>}}] [{nginx-hhvm-wp nginx-hhvm-wp [/scripts/start.sh]  [{ 53306 3306 TCP } { 243 443 TCP } { 280 80 TCP }] [] {map[cpu:{1.000 DecimalSI} memory:{419430400 BinarySI}]} [{www-data false /www} {ssl-certificates true /etc/nginx/ssl} {log-data false /var/log} {sites-enabled-data true /etc/nginx/sites-enabled} {mysql false /var/lib/mysql} {scripts true /scripts}] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Never ClusterFirst map[] } {Pending []     map[]}}Node 127.0.0.1: PodFitsPorts
```
Netstat shows that all required to bind ports are available:

    $ sudo netstat -laputen | egrep '(280|243|53306)'
    $

And pod remains pending:
```
$ kubectl get pods
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS              CREATED
verse-controller                        nginx-hhvm-wp       nginx-hhvm-wp       <unassigned>        name=frontend       Pending             15 seconds
```

Here is my pod definition: 
```json
{
  "id": "verse-controller",
  "kind": "Pod",
  "apiVersion": "v1beta1",
  "desiredState": {
     "manifest": {
       "version": "v1beta1",
       "id": "verse-controller",
       "volumes": [
         {"name": "www-data", "source": {"hostDir" : {"path": "/opt/data/docker-nginx-hhvm-wp/volumes/www"}}},
         {"name": "ssl-certificates", "source": {"hostDir" : {"path": "/opt/data/docker-nginx-hhvm-wp/volumes/ssl"}}},
         {"name": "log-data", "source": {"hostDir" : {"path": "/opt/data/docker-nginx-hhvm-wp/volumes/log"}}},
         {"name": "sites-enabled-data", "source": {"hostDir" : {"path": "/opt/data/docker-nginx-hhvm-wp/volumes/sites-enabled"}}},
         {"name": "mysql", "source": {"hostDir" : {"path": "/opt/data/docker-nginx-hhvm-wp/volumes/mysql"}}},
         {"name": "scripts", "source": {"hostDir" : {"path": "/opt/data/docker-nginx-hhvm-wp/volumes/scripts"}}}
       ],
       "containers": [{
         "name": "nginx-hhvm-wp",
         "image": "nginx-hhvm-wp",
         "command": ["/scripts/start.sh"],
         "cpu": 1000,
         "memory": 419430400, 
         "ports": [{"containerPort": 3306, "hostPort": 53306}, {"containerPort": 443, "hostPort": 243}, {"containerPort": 80, "hostPort": 280}],
         "volumeMounts": [
           {"name": "www-data", "mountPath": "/www", "readOnly": false, "mountType": "HOST"},
           {"name": "ssl-certificates", "mountPath": "/etc/nginx/ssl", "readOnly": true, "mountType": "HOST"},
           {"name": "log-data", "mountPath": "/var/log", "readOnly": false, "mountType": "HOST"},
           {"name": "sites-enabled-data", "mountPath": "/etc/nginx/sites-enabled", "readOnly": true, "mountType": "HOST"},
           {"name": "mysql", "mountPath": "/var/lib/mysql", "readOnly": false, "mountType": "HOST"},
           {"name": "scripts", "mountPath": "/scripts", "readOnly": true, "mountType": "HOST"}
         ]
       }], 
       "restartPolicy": {  
        "Never": {}
      }  
     }
  },
  "labels": {"name": "frontend"}
}
```

**Comment by roberthbailey** [comment]
@bgrant0607 - have there been any recent changes to the scheduler that would have caused this?

**Comment by bprashanth** [comment]
If you deleted and re-created the pod, it's probably fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/5791

**Comment by sumkincpp** [comment]
@bprashanth 
No, it doesn't work either. I am using the folowing commands to recreate pod:
```
$ kubectl delete pod verse-controller
verse-controller
$ kubectl create -f verse-controller.json
verse-controller
```

**Comment by bprashanth** [comment]
Hrm, that sounds like it should be fixed with the pr. If you could sync, apply the patch and confirm it would be great. It sounds like all you're doing is create, delete, create on the same pod right? If the pod is still stuck please upload your kube-scheduler logs in a gist.

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by sumkincpp** [comment]
Latest /master still fails to build release. Need to wait some time till there will be successful build.

**Comment by lavalamp** [comment]
Should be mostly fixed by #6110. Sorry about this.

**Comment by sumkincpp** [comment]
Thanks, fixed for now. Closing this case.
