### ISSUE TITLE
data race in node-controller error handling

### ISSUE THREAD

**Issue by jdef** [GoogleCloudPlatform/kubernetes#6416]
stack trace here: https://github.com/mesosphere/kubernetes-mesos/issues/197#issuecomment-89336229

it's due to a shared `err` variable:
https://github.com/mesosphere/kubernetes-mesos/blob/1ec68d48d69c107df81b7bb5c1269f1072d70bd6/hack/patches/k8s---issue199.patch

**Comment by yujuhong** [comment]
Hi @jdef, thanks for reporting the issue with a patch! Do you want to submit a PR so that you can take the credit for your fix? :)

**Comment by jdef** [comment]
done

On Fri, Apr 3, 2015 at 2:32 PM, Yu-Ju Hong <notifications@github.com> wrote:

> Hi @jdef <https://github.com/jdef>, thanks for reporting the issue with a
> patch! Do you want to submit a PR so that you can take the credit for your
> fix? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/6416#issuecomment-89384407>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by yujuhong** [comment]
@gmarek, FYI, I think the same bug may still exist in your new PR.

**Comment by gmarek** [comment]
There are multiple p

**Comment by gmarek** [comment]
There are multiple PRs in flight, so I don't know which one you have in mind. One of them removes probing logic from controller altogether.

**Comment by yujuhong** [comment]
I was referring to #6058, but I didn't read that PR closely so the bug may longer exist there. Again, just a FYI. :)
