### ISSUE TITLE
ReplicationController e2e tests got flakey on Thusday afternoon

### ISSUE THREAD

**Issue by quinton-hoole** [GoogleCloudPlatform/kubernetes#6424]
The following two e2e tests, which had been 100% stable for many weeks, suddenly started failing ~20% of the time, starting at Thu Apr 3, 9:17pm.

- "ReplicationController should serve a basic image on each replica with a private image"
- "ReplicationController should serve a basic image on each replica with a public image"

Failed runs of these tests all look roughly like this:

"Gave up waiting for hostIP of replica 0 after 120.219885567 seconds"

Details here:

http://jenkins.kubernetes.io/job/kubernetes-e2e-gce/4143/consoleFull

INFO: Controller my-hostname-private-259840e1-da3d-11e4-94c2-42010af01555: Retrying to get the hostIP of replica 1

• Failure [128.618 seconds]
ReplicationController
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:55
  should serve a basic image on each replica with a private image [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:54

  Controller my-hostname-private-259840e1-da3d-11e4-94c2-42010af01555: Gave up waiting for hostIP of replica 0 after 120.219885567 seconds

  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:151

**Comment by quinton-hoole** [comment]
Successful runs of these tests succeed rather quickly, so increasing the timeout here is unlikely to help:

e.g. in 11.474 seconds...

INFO: Controller my-hostname-private-5c17c64d-da42-11e4-88ec-42010af01555: Replica 1 has hostIP: 146.148.62.13
INFO: Controller my-hostname-private-5c17c64d-da42-11e4-88ec-42010af01555: Replica 2 has hostIP: 146.148.62.13
STEP: Trying to dial each unique pod
INFO: Controller my-hostname-private-5c17c64d-da42-11e4-88ec-42010af01555: Got expected result from replica 1: my-hostname-private-5c17c64d-da42-11e4-88ec-42010af01555-1eg85
INFO: Controller my-hostname-private-5c17c64d-da42-11e4-88ec-42010af01555: Got expected result from replica 2: my-hostname-private-5c17c64d-da42-11e4-88ec-42010af01555-sl0yi
STEP: Cleaning up the replication controller

• [SLOW TEST:11.474 seconds]

**Comment by bprashanth** [comment]
It looks like its failing waiting on hostip of a pod, which iirc we call into the cloud provider to get (gce in this case). 
1. Does the test need to verify hostIp, or can we use the state of the pod instead?
2. What happened to the pod?

Looking at the test, the failure most likely has nothing to do with the rc because it got past: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/rc.go#L134, which means the rc created the pods and they were in running. So did they even get scheduled, did the kubelet reject them, or did we only fail to get their host ips?

A decent first step might be to just log what the pod is doing (its phase, host etc), though I still think we should split hostip out into its own test (and maybe just use pod phase for this? dunno just thinking out).

**Comment by quinton-hoole** [comment]
Agreed, the hostip verification doesn't seem necessary in this test.
But it does seem like we have a regression in system behavior yesterday afternoon, which would be worth getting to the bottom of.

I'm going to try to repro the failure locally, and figure out what state the pods were in.

I'm also going to narrow down the regression to a set of candidate PR's.

**Comment by bprashanth** [comment]
Theres a chance I already fixed it with https://github.com/GoogleCloudPlatform/kubernetes/pull/6401 which happened because of  https://github.com/GoogleCloudPlatform/kubernetes/pull/6349 which caused minion watch to fail, without which the kubelet can't populate the hostips of pods on it (allow some margin for error because I've dug through the kubelet/hostip code for lik 60seconds):
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1707

**Comment by quinton-hoole** [comment]
#6401 was merged at 7:06 PM last night (Thu 4/2), and the test is still failing after that, so #6401 doesn't seem to fix the (presumed) bug.

**Comment by quinton-hoole** [comment]
commit de67b96ff716d3d465ad46dbaae668e8586a6556
Merge: d69e716 39bb6d3
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 18:50:30 2015 -0700

    Merge pull request #6396 from ArtfulCoder/master_logging
    
    Enable log collection from master.

commit 5b6c75f98672d4a19ba439d6a0cf006e5e288c97
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 18:40:27 2015 -0700

    And re-tabify that (to make previous easier to review)

commit e57171d2ccf93e27f2d20b4bf64ce6b8d22b7180
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 18:39:40 2015 -0700

    Parallelize Docker build as well

commit 5903f6ff397b880ef14522bf8b7c978bb03cb3c7
Author: Prashanth Balasubramanian <beeps@google.com>
Date:   Thu Apr 2 18:37:28 2015 -0700

    Register field conversion function under the right type name

commit 39bb6d3777bf3f3afea61ac27e8f6f061e593d86

Author: Abhishek Shah <abshah@google.com>
Date:   Thu Apr 2 17:21:13 2015 -0700

    Enable log collection from master.

commit 9a6e04dc1f896b27ff4193c45eeb3a3107338cfa
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 18:18:24 2015 -0700

    Cleanup output of Docker builds, fix #6389

commit 03c7182cac9eda4afdea71c89901b03de44796e4
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 10:52:53 2015 -0700

    Also build entire tarball phases in parallel

commit c0ed73a10d007c1088414719c72369753f571f92
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 08:46:28 2015 -0700

    Only build in parallel if the build machine is >8G

commit e159c02a2a832ef49e0377b318b3b9f597c97458
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 06:51:20 2015 -0700

    Completely neutral commit that just factors each platform build out to
    a function (to make it kinder on reviewers for the next piece).

commit 04813f0dcdbbc4fb104f5dcf2b0d386687fe73f3
Author: Zach Loafman <zml@google.com>
Date:   Thu Apr 2 13:46:39 2015 -0700

    Revert "Revert "Parallelize architectures in both the building and packaging phases of `make release`""
    
    This reverts commit 9f60dde3200a10d84cd5638f3ce81a596023519d.

**Comment by quinton-hoole** [comment]
The above is the set of candidate commits, one or more of which probably caused the regression, based on the time when the test started to fail.

**Comment by zmerlynn** [comment]
So it's #6369 and #6396. A dyslexic somewhere is having nightmares.

**Comment by zmerlynn** [comment]
@quinton-hoole: Your timeline doesn't line up. You seem to be looking at commit times and not the actual commits that are in the tree. My commits, for instance, didn't land in the tree until go/k8s-test/job/kubernetes-build/1416/, which lines up with Jenkins e2e-gce job go/k8s-test/job/kubernetes-e2e-gce/4140/, which is well after the instability started.

**Comment by zmerlynn** [comment]
@quinton-hoole: Yeah, I think the candidates are from: go/k8s-test/kubernetes-build/1407/, which you had one right one: #6396. The other candidate is #6401.

**Comment by bprashanth** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/6401 actually just enabled https://github.com/GoogleCloudPlatform/kubernetes/pull/6349, which was in but not working prior to that. https://github.com/GoogleCloudPlatform/kubernetes/pull/6373 should scope some of those watches, so it's worth re-evaluating with that (if it's anything to do with watch server performance and the fact that we recently started filtering the nodes we watch on the kubelet).

**Comment by quinton-hoole** [comment]
This looks like a re-occurrance of #4785

**Comment by bprashanth** [comment]
Probably a different issue with the same symptoms, that's a pretty stale bug and the node controller's changed up quite a bit since then (also the OP of that bug had a questionable setup)

**Comment by quinton-hoole** [comment]
Resolved by #6712 and #6665
