### ISSUE TITLE
kubectl resize should use resource.Builder to select multiple items

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/kubernetes#8580]
Currently it's only using the first item - but resize should work on multiple items in serial (requiring at least one).  If we change that, we also can't use the len(args) == 2 check (we rely on resource.Bulider for that)

@kargakis

**Comment by smarterclayton** [comment]
Right now, `kubectl resize rc/foo --replicas=2` is broken because of the len(args) == 2 check

**Comment by kargakis** [comment]
> Right now, kubectl resize rc/foo --replicas=2 is broken because of the len(args) == 2 check

Yup, wanted to remove that.

**Comment by kargakis** [comment]
What the story should be with the command's flags? All of them are supposed to work with one item so far...

**Comment by smarterclayton** [comment]
If there are flags that truly don't make sense with multiple items we should error if you provide multiple with that flag.  Replicas is the most likely command though and shouldn't be a problem to provide.

**Comment by kargakis** [comment]
All of the flags in here don't make sense with multiple items. Furthermore, one is mandatory (`--replicas`) needed for specifying the new spec of the provided rc.

**Comment by smarterclayton** [comment]
Why doesn't replicas make sense for multiple rcs?  "I want rcs 1, 2, and 3 to have 5 replicas".

**Comment by kargakis** [comment]
What if a user wants to say "I want rc 1 to have 3 replicas, 2 to have 8 replicas and 3 to have 1 replica"? Is it possible for a flag to maintain a table of multiple values?

**Comment by smarterclayton** [comment]
I don't think we'd support that.  Anyone who wants to do that should call resize multiple times.  The scenario I'm most focused on are homogenous RCs identified by a label selector:

   # resize all of my shards to 3 in the west region (assuming you have multiple rcs with labels like rc=west-1,shard=N)
   kubectl resize rc -l rc=west-1 --replicas=3

   # resize all shards to 0
   kubectl resize rc/west1 rc/west2 --replicas=0


----- Original Message -----

**Comment by bgrant0607** [comment]
I'd take this for 1.0 if you want to try to get it in. Looks easy / low risk.

**Comment by smarterclayton** [comment]
Fixed by #6723

**Comment by kargakis** [comment]
This is not really fixed since right now scale will [error](https://github.com/GoogleCloudPlatform/kubernetes/blob/1c0b765df6dabfe9bd0e20489ed3bd18e6b3bda8/pkg/kubectl/cmd/scale.go#L102-L105) out in case of multiple items. I will submit a PR on Monday fixing it.
